numberOfSubMaps: 1
poi:
  submap_0:
    avoid_that: [submap_0, avoid_that, -2.0, -2.0, 0]
    init_avoid_that: [submap_0, init_avoid_that, -2.0, -2.0, 0]
    init_pick_and_place: [submap_0, init_pick_and_place, -2.0, -2.0, 0]
    init_fetch_and_carry: [submap_0, init_fetch_and_carry, -2.0, -2.0, 0]
    init_find_me: [submap_0, init_find_me, -2.0, -2.0, 0]
    init_what_say: [submap_0, init_what_say, -2.0, -2.0, 0]
    
	

