numberOfPois: 1
pois:
  emergency:
    living_room_1: [emergency, living_room_1, 1, living_room_1]
    living_room_2: [emergency, living_room_2, 2, living_room_2]
    living_room_3: [emergency, living_room_3, 3, living_room_3]
    living_room_4: [emergency, living_room_4, 4, living_room_4]
    living_room_5: [emergency, living_room_5, 5, living_room_5]
