numberOfPois: 1
pois:
  emergency:
    point_room_one: [emergency, point_room_one, point_room_one]
    point_room_two: [emergency, point_room_two, point_room_two]
    point_room_three: [emergency, point_room_three, point_room_three]

