numberOfSubMaps: 1
poi:
  submap_0:
    emergency_room: [submap_0, emergency_room, 1.512, -2.234, 0.269]
    entry_door_init: [submap_0, entry_door_init, -2.027, -7.907, 0]
    entry_door_exit: [submap_0, entry_door_exit, 0.728, -5.800,  1.644]
    kitchen: [submap_0, kitchen, 9.312, -3.289, -0.046]

