numberOfSubMaps: 1
poi:
  submap_0:
    emergency_room: [submap_0, emergency_room, 3.412, -3.231, 0]
    entry_door_init: [submap_0, entry_door_init, -2.027, -7.907, 0]
    entry_door_exit: [submap_0, entry_door_exit, -0.652, -10.121, 0]
    kitchen: [submap_0, kitchen, 9.404, -2.972, 0]

