numberOfSubMaps: 1
poi:
  submap_0:
    emergency_room: [submap_0, emergency_room,-3.349, 1.618,  2.498]
    entry_door_init: [submap_0, entry_door_init, -1.844, 2.280, -0.111]
    entry_door_exit: [submap_0, entry_door_exit, -0.858, 2.203, -0.084]
    kitchen: [submap_0, kitchen, 0.588, 5.408, 1.698]
    hallway: [submap_0, hallway, 0.842, 4.278, 1.641]
    living_room: [submap_0, living_room,1.090, 0.592,  -0.352]
    working_desk: [submap_0, working_desk, 0.79, -6.575, -0.110]
    kitchen_counter: [submap_0, kitchen_counter, 0.79, -6.575, -0.110]
    dinner_table: [submap_0, dinner_table, 0.79, -6.575, -0.110]
    bookshelf: [submap_0, bookshelf,-6.219, 9.137, 0.795]
    point_room_one: [submap_0, point_room_one, -0.758, 7.336, -0.128]
    point_room_two: [submap_0, point_room_two, -0.877, 7.008, -0.662]
    point_room_three: [submap_0, point_room_three, -0.809, 6.411, -1.441]

object:
  information:
    coke: [information, coke, beverage]
    pringles: [information, pringles, snack]
    water: [information, water, beverage]
    Barritas: [information, Barritas, snack]
    cell_phone: [information, cell_phone, utils]
    first_aid_kit: [information, first_aid_kit, utils]
  
  beverage:
    kitchen_counter: [beverage, kitchen_counter, 0.90]
    dinner_table: [beverage, dinner_table, 0.00]

  snack:
    kitchen_counter: [snack, kitchen_counter, 0.90]
    dinner_table: [snack, dinner_table, 0.00]

  utils:
    kitchen_counter: [snack, kitchen_counter, 0.90]
    dinner_table: [snack, dinner_table, 0.00]

