numberOfSubMaps: 1
poi:
  submap_0:
    emergency_room: [submap_0, emergency_room, 1.044, -3.866, 0.761]
    entry_door_init: [submap_0, entry_door_init, -2.027, -7.907, 0]
    entry_door_exit: [submap_0, entry_door_exit, 0.490, -5.997,  1.482]
    kitchen: [submap_0, kitchen, 9.683, -2.959, -1.578]

