numberOfSubMaps: 1
poi:
  submap_0:
    emergency_room: [submap_0, emergency_room, 3.0, 3.0, 0]
    entry_door_init: [submap_0, entry_door, -3.0, 0.0, 0]
    entry_door_exit: [submap_0, entry_door_2, -3.0, 2, 0]
    kitchen: [submap_0, kitchen, 5.0, 4.0, 0]


