numberOfSubMaps: 1
poi:
  submap_0:
    init_avoid_that: [submap_0, init_avoid_that, -3.349, 1.618, 2.498]
    avoid_that: [submap_0, avoid_that, -7.298, 5.911,  -2.252]

    init_pick_and_place: [submap_0, init_pick_and_place, -2.0, -2.0, 0]
    pick_and_place: [submap_0, pick_and_place, -2.0, -2.0, 0]
    waste_bin: [submap_0, waste_bin, -2.0, -2.0, 0] 

    init_fetch_and_carry: [submap_0, init_fetch_and_carry, -2.0, -2.0, 0]
    fetch_and_carry: [submap_0, fetch_and_carry, -2.0, -2.0, 0]

    init_find_me: [submap_0, init_find_me, -1.521, 7.646, 2]
    find_me: [submap_0, find_me, -1.521, 7.646,  1]

    init_what_say: [submap_0, init_what_say,  -1.521, 7.646,  -0.620]

    point_room_one: [submap_0, point_room_one, -1.126, 8.635, -1.568]
    point_room_two: [submap_0, point_room_two, -1.964, 7.885, -0.642]
    point_room_three: [submap_0, point_room_three, -1.779, 7.432, -1.134]

