numberOfSubMaps: 1
poi:
  submap_0:
    init_avoid_that: [submap_0, init_avoid_that, -3.349, 1.618, 2.498]
    avoid_that: [submap_0, avoid_that, -7.298, 5.911,  -2.252]

    init_pick_and_place: [submap_0, init_pick_and_place, -2.0, -2.0, 0]
    pick_and_place: [submap_0, pick_and_place, -0.540, 4.428, -2.252]
    waste_bin: [submap_0, waste_bin, 1.20, 4.84, 0.0] 

    init_fetch_and_carry: [submap_0, init_fetch_and_carry, -2.0, -2.0, 0]
    fetch_and_carry: [submap_0, fetch_and_carry, -2.0, -2.0, 0]

    init_find_me: [submap_0, init_find_me,-1.521, 7.646,  -0.620]
    find_me: [submap_0, find_me, -1.521, 7.646,  -0.620]

    init_what_say: [submap_0, init_what_say,  -1.521, 7.646,  -0.620]

    entry_door_init: [submap_0, entry_door_init, 3.705, -0.694, 0.06]
    entry_door_exit: [submap_0, entry_door_exit,7.017, -0.472, 0.051]
    kitchen: [submap_0, kitchen,17.686, -1.135, -1.620]
    hallway: [submap_0, hallway, 14.910, -1.393, -1.603]
    living_room: [submap_0, living_room, 9.955, -1.491,  -0.966]
    working_desk: [submap_0, working_desk, 10.320, -8.315,  -1.459]
    kitchen_counter: [submap_0, kitchen_counter,10.320, -8.315,  -1.459]
    dinner_table: [submap_0, dinner_table, 10.320, -8.315,  -1.459]
    bookshelf: [submap_0, bookshelf, 9.079, -6.977, -0.065]
    point_room_one: [submap_0, point_room_one, 7.910, 6.254, 0.709]
    point_room_two: [submap_0, point_room_two, 8.476, 5.305, -0.767]
    point_room_three: [submap_0, point_room_three, -0.809, 6.411, -1.441]

object:
  information:
    Coke: [information, Coke, pick_and_place, beverage]
    Pringles: [information, Pringles, pick_and_place,snack]

  beverage:
    kitchen_counter: [beverage, kitchen_counter, 0.90]

  snack:
    dinner_table: [snack, dinner_table, 0.90]
  
  pick_and_place:
    pick_and_place: [pick_and_place, pick_and_place, 1]

