numberOfSubQuestions: 1
questions:
  what_say_simple:
    one:   [what_say_simple, one,   1,   Time]
    two:   [what_say_simple, two,   2,   "Reem Golem"]
    three: [what_say_simple, three, 3,   Brasilia]
    four:  [what_say_simple, four,  4,   "1997"]
    five:  [what_say_simple, five,  5,   "5"]
    six:   [what_say_simple, six,   6,   "42"]
    seven: [what_say_simple, seven, 7,   Lettuce]
    eight: [what_say_simple, eight, 8,   Alcohol]
    nine: [what_say_simple, nine, 9,   Dragonfly]
    ten: [what_say_simple, ten, 10,   "Spongebob Squarepants"]
