numberOfSubMaps: 1
poi:
  submap_0:
    party_room: [submap_0, party_room, 5.672,-8.394, 1.399]
    storage_room: [submap_0, storage_room,  12.927,-7.445,  1.708]
    leave_room: [submap_0, leave_room,5.362, -9.159, -1.450]
    kitchen_counter: [submap_0, kitchen_counter, 10.954, -6.4517,  1.500]
    dinner_table: [submap_0, dinner_table,10.954, -6.4517,  1.500]

object:
  information:
    Coke: [information, Coke, beverage]
    Pringles: [information, Pringles, snack]
    Barritas: [information, Barritas, snack]

  beverage:
    kitchen_counter: [beverage, kitchen_counter, 0.90]
    dinner_table: [beverage, dinner_table, 0.00]

  snack:
    kitchen_counter: [beverage, kitchen_counter, 0.90]
    dinner_table: [beverage, dinner_table, 0.00]

