numberOfSubMaps: 1
poi:
  submap_0:
    ordering: [submap_0, ordering, 3.0, -3.0, 0]

object:
  information:
    coke: [information, coke, drinks]
    fanta: [information, fanta, drinks]
    beer: [information, beer, drinks]
    water: [information, water, drinks]
    cookies: [information, cookies, snacks]


