sentence0: "Move to the kitchen, then go to the kitchen and exit the apartment" 
sentence1: "Move to the kitchen, then move to the kitchen and leave the apartment" 
sentence2: "Move to the kitchen, then move to the kitchen and exit the apartment" 
sentence3: "Move to the kitchen, then navigate to the kitchen and leave the apartment" 
sentence4: "Move to the kitchen, then navigate to the kitchen and exit the apartment" 
sentence5: "Navigate to the kitchen, then go to the kitchen and leave the apartment" 
sentence6: "Navigate to the kitchen, then go to the kitchen and exit the apartment" 
sentence7: "Navigate to the kitchen, then move to the kitchen and leave the apartment" 
sentence8: "Navigate to the kitchen, then move to the kitchen and exit the apartment" 
sentence9: "Navigate to the kitchen, then navigate to the kitchen and leave the apartment" 
sentence10: "Navigate to the kitchen, then navigate to the kitchen and exit the apartment" 
sentence11: "Go to the kitchen, get the coke, and leave the apartment" 
sentence12: "Go to the kitchen, get the coke, and exit the apartment" 
sentence13: "Go to the kitchen, take the coke, and leave the apartment" 
sentence14: "Go to the kitchen, take the coke, and exit the apartment" 
sentence15: "Go to the kitchen, grasp the coke, and leave the apartment" 
sentence16: "Go to the kitchen, grasp the coke, and exit the apartment" 
sentence17: "Move to the kitchen, get the coke, and leave the apartment" 
sentence18: "Move to the kitchen, get the coke, and exit the apartment" 
sentence19: "Move to the kitchen, take the coke, and leave the apartment" 
sentence20: "Move to the kitchen, take the coke, and exit the apartment" 
sentence21: "Move to the kitchen, grasp the coke, and leave the apartment" 
sentence22: "Move to the kitchen, grasp the coke, and exit the apartment" 
sentence23: "Navigate to the kitchen, get the coke, and leave the apartment" 
sentence24: "Navigate to the kitchen, get the coke, and exit the apartment" 
sentence25: "Navigate to the kitchen, take the coke, and leave the apartment" 
sentence26: "Navigate to the kitchen, take the coke, and exit the apartment" 
sentence27: "Navigate to the kitchen, grasp the coke, and leave the apartment" 
sentence28: "Navigate to the kitchen, grasp the coke, and exit the apartment" 
sentence29: "Go to the kitchen, introduce yourself, and leave the apartment" 
sentence30: "Go to the kitchen, introduce yourself, and exit the apartment" 
sentence31: "Go to the kitchen, tell something about yourself, and leave the apartment" 
sentence32: "Go to the kitchen, tell something about yourself, and exit the apartment" 
sentence33: "Move to the kitchen, introduce yourself, and leave the apartment" 
sentence34: "Move to the kitchen, introduce yourself, and exit the apartment" 
sentence35: "Move to the kitchen, tell something about yourself, and leave the apartment"
sentence36: "Move to the kitchen, tell something about yourself, and exit the apartment" 
sentence37: "Navigate to the kitchen, introduce yourself, and leave the apartment" 
sentence38: "Navigate to the kitchen, introduce yourself, and exit the apartment" 
sentence39: "Navigate to the kitchen, tell something about yourself, and leave the apartment" 
sentence40: "Navigate to the kitchen, tell something about yourself, and exit the apartment" 
sentence41: "Go to the kitchen, memorize the person, and recognize him"
sentence42: "Go to the kitchen, ask the person name, and recognize him"
sentence43: "Move to the kitchen, memorize the person, and recognize him"
sentence44: "Move to the kitchen, ask the person name, and recognize him"
sentence45: "Navigate to the kitchen, memorize the person, and recognize him"
sentence46: "Navigate to the kitchen, ask the person name, and recognize him"
sentence47: "Go to the kitchen, introduce yourself, and follow the person in front of you"
sentence48: "Go to the kitchen, tell something about yourself, and follow the person in front of you"
sentence49: "Move to the kitchen, introduce yourself, and follow the person in front of you"
sentence50: "Move to the kitchen, tell something about yourself, and follow the person in front of you"
sentence51: "Navigate to the kitchen, introduce yourself, and follow the person in front of you"
sentence52: "Navigate to the kitchen, tell something about yourself, and follow the person in front of you"
sentence53: "Memorize the person, follow the person in front of you, and leave the apartment"
sentence54: "Memorize the person, follow the person in front of you, and exit the apartment"
sentence55: "Ask the person name, follow the person in front of you, and leave the apartment"
sentence56: "Ask the person name, follow the person in front of you, and exit the apartment"
sentence57: "Find a person, retrieve the coke from the kitchen, and leave the apartment"
sentence58: "Find a person, retrieve the coke from the kitchen, and exit the apartment"
sentence59: "Find a person, bring the coke from the kitchen, and leave the apartment"
sentence60: "Find a person, bring the coke from the kitchen, and exit the apartment"
sentence61: "Go to the kitchen, find a person, and retrieve the coke from the kitchen"
sentence62: "Go to the kitchen, find a person, and bring the coke from the kitchen"
sentence63: "Move to the kitchen, find a person, and retrieve the coke from the kitchen"
sentence64: "Move to the kitchen, find a person, and bring the coke from the kitchen"
sentence65: "Navigate to the kitchen, find a person, and retrieve the coke from the kitchen"
sentence66: "Navigate to the kitchen, find a person, and bring the coke from the kitchen"
sentence67: "Memorize the person, follow the person in front of you, and leave the apartment"
sentence68: "Memorize the person, follow the person in front of you, and exit the apartment"
sentence69: "Ask the person name, follow the person in front of you, and leave the apartment"
sentence70: "Ask the person name, follow the person in front of you, and exit the apartment"
sentence71: "Go to the kitchen, find a person, and introduce yourself"
sentence72: "Go to the kitchen, find a person, and tell something about yourself"
sentence73: "Move to the kitchen, find a person, and introduce yourself"
sentence74: "Move to the kitchen, find a person, and tell something about yourself"
sentence75: "Navigate to the kitchen, find a person, and introduce yourself"
sentence76: "Navigate to the kitchen, find a person, and tell something about yourself"
sentence77: "Get the coke, bring it to the kitchen, and introduce yourself"
sentence78: "Get the coke, bring it to the kitchen, and tell something about yourself"
sentence79: "Get the coke, carry it to the kitchen, and introduce yourself"
sentence80: "Get the coke, carry it to the kitchen, and tell something about yourself"
sentence81: "Take the coke, bring it to the kitchen, and introduce yourself"
sentence82: "Take the coke, bring it to the kitchen, and tell something about yourself"
sentence83: "Take the coke, carry it to the kitchen, and introduce yourself"
sentence84: "Take the coke, carry it to the kitchen, and tell something about yourself"
sentence85: "Grasp the coke, bring it to the kitchen, and introduce yourself"
sentence86: "Grasp the coke, bring it to the kitchen, and tell something about yourself"
sentence87: "Grasp the coke, carry it to the kitchen, and introduce yourself"
sentence88: "Grasp the coke, carry it to the kitchen, and tell something about yourself"
sentence89: "Go to the kitchen, get the coke, and bring it to the kitchen"
sentence90: "Go to the kitchen, get the coke, and carry it to the kitchen"
sentence91: "Go to the kitchen, take the coke, and bring it to the kitchen"
sentence92: "Go to the kitchen, take the coke, and carry it to the kitchen"
sentence93: "Go to the kitchen, grasp the coke, and bring it to the kitchen"
sentence94: "Go to the kitchen, grasp the coke, and carry it to the kitchen"
sentence95: "Move to the kitchen, get the coke, and bring it to the kitchen"
sentence96: "Move to the kitchen, get the coke, and carry it to the kitchen"
sentence97: "Move to the kitchen, take the coke, and bring it to the kitchen"
sentence98: "Move to the kitchen, take the coke, and carry it to the kitchen"
sentence99: "Move to the kitchen, grasp the coke, and bring it to the kitchen"
sentence100: "Move to the kitchen, grasp the coke, and carry it to the kitchen"
sentence101: "Navigate to the kitchen, get the coke, and bring it to the kitchen"
sentence102: "Navigate to the kitchen, get the coke, and carry it to the kitchen"
sentence103: "Navigate to the kitchen, take the coke, and bring it to the kitchen"
sentence104: "Navigate to the kitchen, take the coke, and carry it to the kitchen"
sentence105: "Navigate to the kitchen, grasp the coke, and bring it to the kitchen"
sentence106: "Navigate to the kitchen, grasp the coke, and carry it to the kitchen"
sentence107: "Go to the kitchen, detect the coke, and get it"
sentence108: "Go to the kitchen, detect the coke, and take it"
sentence109: "Go to the kitchen, detect the coke, and grasp it"
sentence110: "Go to the kitchen, find the coke, and get it"
sentence111: "Go to the kitchen, find the coke, and take it"
sentence112: "Go to the kitchen, find the coke, and grasp it"
sentence113: "Go to the kitchen, identify the coke, and get it"
sentence114: "Go to the kitchen, identify the coke, and take it"
sentence115: "Go to the kitchen, identify the coke, and grasp it"
sentence116: "Move to the kitchen, detect the coke, and get it"
sentence117: "Move to the kitchen, detect the coke, and take it"
sentence118: "Move to the kitchen, detect the coke, and grasp it"
sentence119: "Move to the kitchen, find the coke, and get it"
sentence120: "Move to the kitchen, find the coke, and take it"
sentence121: "Move to the kitchen, find the coke, and grasp it"
sentence122: "Move to the kitchen, identify the coke, and get it"
sentence123: "Move to the kitchen, identify the coke, and take it"
sentence124: "Move to the kitchen, identify the coke, and grasp it"
sentence125: "Navigate to the kitchen, detect the coke, and get it"
sentence126: "Navigate to the kitchen, detect the coke, and take it"
sentence127: "Navigate to the kitchen, detect the coke, and grasp it"
sentence128: "Navigate to the kitchen, find the coke, and get it"
sentence129: "Navigate to the kitchen, find the coke, and take it"
sentence130: "Navigate to the kitchen, find the coke, and grasp it"
sentence131: "Navigate to the kitchen, identify the coke, and get it"
sentence132: "Navigate to the kitchen, identify the coke, and take it"
sentence133: "Navigate to the kitchen, identify the coke, and grasp it"
sentence134: "Go to the kitchen, then go to the kitchen and leave the apartment"
sentence135: "Go to the kitchen, then go to the kitchen and exit the apartment"
sentence136: "Go to the kitchen, then move to the kitchen and leave the apartment"
sentence137: "Go to the kitchen, then move to the kitchen and exit the apartment"
sentence138: "Go to the kitchen, then navigate to the kitchen and leave the apartment"
sentence139: "Go to the kitchen, then navigate to the kitchen and exit the apartment"
sentence140: "Move to the kitchen, then go to the kitchen and leave the apartment"
