sentence0: "Bring a drink to a table" 
sentence1: "Bring a drink to a shelf" 
sentence2: "Bring a drink to a door" 
sentence3: "Bring a drink to an appliance" 
sentence4: "Bring a snack to a seat" 
sentence5: "Bring a snack to a table" 
sentence6: "Bring a snack to a shelf" 
sentence7: "Bring a snack to a door" 
sentence8: "Bring a snack to an appliance" 
sentence9: "Bring the kitchenware to a seat" 
sentence10: "Bring the kitchenware to a table" 
sentence11: "Bring the kitchenware to a shelf" 
sentence12: "Bring the kitchenware to a door" 
sentence13: "Bring the kitchenware to an appliance" 
sentence14: "Bring some food to a seat" 
sentence15: "Bring some food to a table" 
sentence16: "Bring some food to a shelf" 
sentence17: "Bring some food to a door" 
sentence18: "Bring some food to an appliance" 
sentence19: "Carry a drink to a seat" 
sentence20: "Carry a drink to a table" 
sentence21: "Carry a drink to a shelf" 
sentence22: "Carry a drink to a door" 
sentence23: "Carry a drink to an appliance" 
sentence24: "Carry a snack to a seat" 
sentence25: "Carry a snack to a table" 
sentence26: "Carry a snack to a shelf" 
sentence27: "Carry a snack to a door" 
sentence28: "Carry a snack to an appliance" 
sentence29: "Carry the kitchenware to a seat" 
sentence30: "Carry the kitchenware to a table" 
sentence31: "Carry the kitchenware to a shelf" 
sentence32: "Carry the kitchenware to a door" 
sentence33: "Carry the kitchenware to an appliance"
sentence34: "Carry some food to a seat" 
sentence35: "Carry some food to a table" 
sentence36: "Carry some food to a shelf" 
sentence37: "Carry some food to a door" 
sentence38: "Carry some food to an appliance" 
sentence39: "Get me a drink" 
sentence40: "Get me a snack" 
sentence41: "Get me the kitchenware" 
sentence42: "Get me some food" 
sentence43: "Give me a drink" 
sentence44: "Give me a snack"
sentence45: "Give me the kitchenware" 
sentence46: "Give me some food" 
sentence47: "Point at a seat"
sentence48: "Point at a table"
sentence49: "Point at a shelf"
sentence50: "Point at a door"
sentence51: "Point at an appliance"
sentence52: "Go to an exit" 
sentence53: "Move to an exit" 
sentence54: "Navigate to an exit" 
sentence55: "Detect a drink" 
sentence56: "Detect a snack" 
sentence57: "Detect the kitchenware"
sentence58: "Detect some food" 
sentence59: "Find a drink"
sentence60: "Find a snack" 
sentence61: "Find the kitchenware" 
sentence62: "Find some food" 
sentence63: "Bring a drink to a seat" 
