ASR_LOOP: True
ASR_ON: "False"
sentence0: "retrieve the coke from the sofa, and leave the apartment"
sentence: "Go to the sofa, detect the coke, and get it"
sentence2: "go to the sofa and follow the person in front of you"
sentence3: "bring the coke to a sofa"
sentence4: "go to the sofa, grasp the coke bring the coke to bookshelf"  
sentence5: "Bring the kitchenware to a table"
sentence6: "Bring a snack to a seat"
sentence7: "Go to the bar, ask the person name, and recognize him"



