ASR_LOOP: True
ASR_ON: "False"
GRAMATICA: "robocup/minimals"

sentence10: "go to the kitchen"
sentence: "grasp the pringles"
sentence11: "bring me the pringles"
sentence12: "bring the pringles to the dinner table"
sentence13: "find a coke"
sentence14: "find me"
sentence15: "find donald"
sentence16: "point at me"
sentence17: "ask my name"
sentence18: "follow me"
sentence19: "introduce yourself"
sentence20: "learn donald"
sentence21: "recognize donald"
sentence0: "retrieve the coke from the sofa, and leave the apartment"
sentence1: "Go to the kitchen, find a person and guide it to the exit"
sentence2: "go to the sofa and follow the person in front of you"
sentence3: "bring the coke to a sofa"
sentence4: "go to the sofa, grasp the coke bring the coke to bookshelf"  
sentence5: "Bring the kitchenware to a table"
sentence6: "Bring a snack to a seat"
sentence7: "Go to the bar, ask the person name, and recognize him"

notes: "FILES TO TAKE INTO ACCOUNT WHEN PREPARING GPSR: robocup_params.yaml, pois_gpsr.yaml, newGrammar.cfg, general.gram/minimals.gram (to change between them HERE or in files:sm_gpsr_order, newUnderstanding, grammarReader, gpsrASAction)"

nota: "If executing test (hardcoded in sm_gpsr_order) there are some locations and objects hardcoded"



