ASR_LOOP: True
ASR_ON: "False"
GRAMATICA: "robocup/minimals"

sentence: "move to the kitchen, grasp the pringles and bring it to the exit"
sentence1: "Go to the kitchen, find a person and guide it to the exit"
sentence2: "go to the sofa and follow the person in front of you"
sentence3: "bring the coke to a armchair"
sentence4: "go to the sofa, grasp the coke bring the coke to bookshelf"  
sentence5: "Bring the kitchenware to a table"
sentence6: "Bring a snack to a seat"
sentence7: "Go to the bar, ask the person name, and recognize him"


sentenceT1_CAT1: "Move to the LOCATION, move to the LOCATION, and move to the LOCATION"
sentenceT2_CAT1: "Move to the LOCATION, move to the LOCATION and leave the apartment"
sentenceT3_CAT1: "Move to the LOCATION, grasp the ITEM, and bring it to me"
sentenceT4_CAT1: "Move to the LOCATION, grasp the ITEM, and bring it to the LOCATION"
sentenceT5_CAT1: "Move to the LOCATION, grasp the ITEM, and put it in the trash bin"
sentenceT6_CAT1: "Move to the LOCATION, find a person, and introduce yourself"
sentenceT7_CAT1: "Move to the LOCATION, find a person, and guide it to the exit"

sentenceT8_CAT2: "Bring me some ITEM_CATEGORY from a LOCATION_CATEGORY.



notes: "FILES TO TAKE INTO ACCOUNT WHEN PREPARING GPSR: robocup_params.yaml, pois_gpsr.yaml, newGrammar.cfg, general.gram/minimals.gram, locations.gram, grammars in speech_states/grammar/robocup/gpsr folder"

nottes: "Remmember to add categories in each grammar, for exemple apart from sofa add seat"

nota: "If executing test (hardcoded in sm_gpsr_order) there are some locations and objects hardcoded"



