ASR_LOOP: True
ASR_ON: "True"
#sentence: "Go to an exit"
sentence: "Get me a drink"
#sentence: "Move to the sofa, then go to the fridge and exit the apartment"
#sentence: "Introduce yourself then grasp a coke and bring it to me"









sentence0: "bring me a coke" #MOLAAA
sentence1: "find a person then memorize the person and recognize him" #KOOOOO
sentence2: "grasp the coke bring the coke to business and tell something about yourself"  #KOOOOO (bussiness no mola)
sentence3: "bring the coke to a sofa" #KOOOOO (keixarnos que no estem portan a una persona)
sentence4: "grasp the coke bring the coke to bookshelf and tell something about yourself" #ko  
sentence5: "Bring the kitchenary to a table" #ko soar don't like kitchenary
sentence6: "Bring a snack to a seat" #ko
sentence7: "Go to the bar, ask the person name, and recognize him" #KOOOO no pot fer lern person
sentence8: "Go to the bar, introduce yourself, and follow the person in front of you" #KOOOO follow person no va

