numberOfSubMaps: 1
poi:
  submap_0:
    kitchen_table: [submap_0, kitchen_table, -12.425, -1.567, -1.298]
    referee: [submap_0, referee, -7.273, -5.443, -2.887]
    pantry: [submap_0, pantry, -7.273, -5.443, -2.887]
    trash_bin: [submap_0, trash_bin, -11.730, -0.015, -3.073]
    armchair: [submap_0, armchair, -6.245, -2.033, -0.472]
    lift: [submap_0, lift, -7.273, -5.443, -2.887]
    exit: [submap_0, exit, -1.418, -0.317,  0.189]
    entrance: [submap_0, entrance, -2.186, 5.614, -2.991]
    emergency_room: [submap_0, emergency_room, -7.273, -5.443, -2.887]
    entry_door_init: [submap_0, entry_door_init, -2.186, 5.614, -2.991]
    entry_door_exit: [submap_0, entry_door_exit, -1.418, -0.317,  0.189]
    kitchen: [submap_0, kitchen,-12.104, -1.112, 1.875]
    hallway: [submap_0, hallway, -4.510, 6.899, 1.820]
    living_room: [submap_0, living_room, -5.148, -0.037, -1.338]
    working_desk: [submap_0, working_desk, -7.273, -5.443, -2.887]
    kitchen_counter: [submap_0, kitchen_counter, -11.504, -0.195, 0.197]
    dinner_table: [submap_0, dinner_table, -7.273, -5.443, -2.887]
    bookshelf: [submap_0, bookshelf, -2.641, -8.758, -1.438]
    

