numberOfSubMaps: 1
poi:
  submap_0:
    hallway: [submap_0, hallway, 3.063, -7.688, 0.566]
    hallway_table: [submap_0, hallway_table, 2.386, -7,467, -1.461]
    kitchen: [submap_0, kitchen, 3.119, -1.072, -1.576]
    kitchen_table: [submap_0, kitchen_table, 2.582, -3.284, -0.027]
    fridge: [submap_0, fridge, 2.992, -5.278, 3.062]
    stove: [submap_0, stove, 2.562, -2.855, -3.113]
    kitchen_counter: [submap_0, kitchen_counter, 2.614, -3.96, -3.091]
    bar: [submap_0, bar, 3.372, -0.385, 1.651]
    waste_bin: [submap_0, waste_bin, 2.479, -2.004, 3.138]
    bedroom: [submap_0, bed_room, 5.771, -7.169, 0.030]
    right_side_table: [submap_0, right_sidetable, 6.434, -8.174, -1.461]
    left_side_table: [submap_0, left_sidetable, 8.050, -8.090, -1.461]
    bed: [submap_0, bed, 6.151, -7.779, -0.027]
    living_room: [submap_0, living_room, 5.704, -2.363, -0.165]
    dinner_table: [submap_0, dinner_table, 5.275, -4.441, -0.030]
    side_board: [submap_0, sideboard, 7.928, -2.516, 0.046]
    armchair: [submap_0, armchair, 6.080, -1.945, 1.591]
    couch_table: [submap_0, couch_table, 7.073, -2.086, 1.600]
    sofa: [submap_0, sofa, 5.696, 0.090, 0.007]
    entrance: [submap_0, door_A, 0.442, -0.023,  0.016]
    exit: [submap_0, door_exit, 2.426, -8.752, -3.091]
    door_B: [submap_0, door_B, 0.753, -8.884,  3.113]
    referee: [submap_0, door_A, 0.442, -0.023,  0.016]
    

