numberOfSubMaps: 1
poi:
  submap_0:
    hallway_table: [submap_0, hallway_table, 1.000, -1.000, 0.197]
    kitchen_table: [submap_0, kitchen_table, 4.744, -3.836, -3.012]
    kitchen_counter: [submap_0, kitchen_counter, 0.308, 0.097, 0.158]
    bar: [submap_0, bar, 2.805, -8.339,  -3.070]
    side_board: [submap_0, side_board, 6.886, -3.320, 0.064]
    stove: [submap_0, stove, 7.630, -1.286, 0.089]
    couch_table: [submap_0, couch_table, -12.425, -1.567, -1.298]
    dinner_table: [submap_0, dinner_table, -7.273, -5.443, -2.887]
    bed: [submap_0, bed, -11.730, -0.015, -3.073]
    left_side_table: [submap_0, left_side_table, -6.245, -2.033, -0.472]
    right_side_table: [submap_0, right_side_table, -7.273, -5.443, -2.887]
    sofa: [submap_0, sofa, -7.273, -5.443, -2.887]
    armchair: [submap_0, armchair, -2.186, 5.614, -2.991]
    fridge: [submap_0, fridge, -1.418, -0.317,  0.189]
    waste_bin: [submap_0, waste_bin, -4.510, 6.899, 1.820]
    referee: [submap_0, referee, -7.273, -5.443, -2.887]
    entrance: [submap_0, entrance, -11.504, -0.195, 0.197]
    exit: [submap_0, exit, -2.641, -8.758, -1.438]
    hallway: [submap_0, hallway, 0.000, 0.000, 0.197]
    kitchen: [submap_0, kitchen, -2.641, -8.758, -1.438]
    bedroom: [submap_0, bedroom, -11.504, -0.195, 0.197]
    living_room: [submap_0, living_room, -2.641, -8.758, -1.438]
    

