locations: ["kitchen_table", "kitchen_counter", "kitchen", "hallway", "bookshelf", "living_room", "armchair", "pantry", "dinner_table", "working_desk", "lift", "entrance", "exit", "referee", "trash_bin"]

items: ["coke", "coke_zero", "juice", "energy_drink", "aquarius", "fanta", "pringles", "beans_can", "cookies", "medicine", "mug", "cup"]

persons: [ "andrew", "charles", "george", "amanda", "hannah", "donald", "frank", "james", "samuel", "deborah", "michelle", "rebecca", "taylor", "paul", "edward", "referee", "person"]

rooms: ["kitchen", "hallway", "living room"]

room:
    kitchen: ["kitchen table", "kitchen counter"]
    living: ["pantry", "armchair", "bookshelf", "dinner table"]
    bedroom: ["sideboard", "bed", "drawer"]


location:
    living room: ["soda"]
    kitchen: ["spoons", "glass"]


it_category:
        drink: ["coke", "coke zero", "juice", "energy drink", "aquarius", "fanta"]
        food: ["pringles", "beans can", "cookies"]
        utils: ["medicine", "mug", "cup"]

loc_category:
        table: ["kitchen table", "dinner table", "working desk"]
        shelf: ["kitchen counter","bookshelf", "pantry"]
        seat: ["armchair"]
        seating: ["armchair"]
        door: ["exit", "entrance"]

kitchen_table_high: 1
dinner_table_high: 1
working_desk_high: 1




