locations: ["hallway_table", "kitchen_table", "kitchen_counter", "bar", "side_board", "stove", "couch_table", "dinner_table", "bed", "left_side_table", "right_side_table", "sofa", "armchair", "fridge", "waste_bin", "referee", "table", "shelf", "appliance", "seating", "entrance", "exit", "hallway", "kitchen", "bedroom", "living_room"]

items: ["brush", "detergent", "shampoo", "sponge", "toothpaste", "cola", "beer", "chocolate_milk", "energy_drink", "grape_juice", "milk", "orange_juice", "water", "chips", "biscuits", "bread", "chocolate_cookies", "pringles", "strawberry_cookies", "baby_food", "beans", "coffee", "crackers", "noodles", "yeast", "cleaning_stuff", "drink", "food", "snaks"]

persons: [ "anna", "beth", "carmen", "jennifer", "jessica", "kimberly", "kristina", "laura", "mary", "sarah", "alfred", "charles", "daniel", "james", "jhon", "luis", "paul", "richard", "robert", "steve", "person", "referee"]

rooms: ["kitchen", "living room", "hallway", "bedroom"]

room:
    kitchen: ["kitchen counter", "bar"]
    living room: ["side board"]
    hallway: ["hallway table"]
    bedroom: ["right side table"]


location:
    living room: ["soda"]
    kitchen: ["spoons", "glass"]


it_category:
        cleaning_stuff: ["brush", "detergent", "shampoo", "sponge", "toothpaste"]
        drink: ["cola", "beer", "chocolate milk", "energy drink", "grape juice", "milk", "orange juice", "water"]
        food: ["baby food", "beans", "coffee", "crackers", "noodles", "yeast"]
        snaks: ["chips", "biscuits", "bread", "chocolate cookies", "pringles", "strawberry cookies"]

loc_category:
        table: ["hallway table", "kitchen table", "couch table", "dinner table"]
        shelf: ["kitchen counter", "bar", "side board", "left side table", "right side table"]
        seating: ["bed", "sofa", "armchair"]
        appliance: ["stove", "fridge", "waste bin"]
        door: ["exit", "entrance"]

hallway_table_heigh: 0.90
kitchen_table_heigh: 0.87
kitchen_counter_heigh: 1
bar_heigh: 0.93
sideboard_heigh: 0.74
stove_heigh: 0.93
couch_table_heigh: 0.70
dinner_table_heigh: 0.87
bed_heigh: 0.77
left_sidetable_heigh: 0.77
right_sidetable_heigh: 0.77

place:
  hallway_table: [place, hallway_table, 2.478, 0.90, 1.0]
  kitchen_table: [place, kitchen_table, 0.75, 0.87, 1.0]
  kitchen_counter: [place, kitchen_counter, 0.75, 1.0, 1.0]
  bar: [place, bar, 0.75, 0.93, 1.0]
  sideboard: [place, sideboard, 9.079, 0.74, 1.0]
  stove: [place, stove, 17.686, 0.93, 1.0]
  couch_table: [place, couch_table, 9.079, 0.40, 1.0]
  dinner_table: [place, dinner_table, 9.079, 0.77, 1.0]
  right_sidetable: [place, right_sidetable, 9.079, 0.77, 1.0]
  left_sidetable: [place, left_sidetable, 9.079, 0.777, 1.0]
  bed: [place, bed, 9.079, 0.87, 1.0]



